# Generated by Django 4.2.8 on 2023-12-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
